version: '3.1'



services:

  db:
    image: postgres
    container_name: postgresdb
    restart: always
    environment:
      - "POSTGRES_PASSWORD=noussair"
      - "POSTGRES_USER=crud_go"
    ports:
      - 5432:5432


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
